name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch: # 允许手动触发

# 权限设置：为 PyPI 的 Trusted Publishing 准备
permissions:
  id-token: write # 用于 OIDC 认证
  contents: read # 允许读取仓库内容

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} (${{ matrix.arch }})
    # 在多个操作系统上运行
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # 一个失败不影响其他
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [auto] # 让 cibuildwheel 自动检测架构

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史记录，可能对版本号有用

      # 使用 pypa/cibuildwheel action 来构建
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          # --- cibuildwheel 配置 (根据你的需要调整) ---
          CIBW_BUILD: cp38-* cp39-* cp310-* cp311-* cp312-* # 构建的 Python 版本范围
          CIBW_ARCHS_MACOS: x86_64 arm64 # 尝试构建 macOS universal2
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014 # 使用兼容性好的 Linux 镜像
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014 # Linux ARM 镜像

      # 将构建好的 wheels 作为 artifact 上传，方便后续 Job 使用或手动下载
      - name: Upload wheels artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl # cibuildwheel 默认输出到 wheelhouse

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest # 在 Linux 上构建 sdist 通常足够
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 使用一个版本来构建 sdist

      - name: Install build dependencies
        run: python -m pip install build setuptools wheel pybind11 # 确保 build 依赖可用

      - name: Build sdist
        run: python -m build --sdist --outdir dist .

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  pypi-publish:
    name: Publish distributions to PyPI
    # 需要 wheels 和 sdist 都构建成功
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    # 使用 PyPI 的 Trusted Publishing 环境
    environment:
      name: pypi
      url: https://pypi.org/project/cppjieba-py-dat

    permissions:
      id-token: write # 必需权限

    steps:
      # 下载所有构建好的 wheels artifacts
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-* # 匹配所有 wheels-os-arch 模式的 artifact
          path: dist/wheels # 下载到 dist/wheels 子目录
          merge-multiple: true # 合并所有 artifact 到一个目录

      # 下载 sdist artifact
      - name: Download sdist artifact
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist # 下载到 dist 目录

      # 将 wheels 移动到主 dist 目录 (pypi-publish action 期望的)
      - name: Move wheels to dist
        run: mv dist/wheels/* dist/

      # 查看最终要上传的文件列表
      - name: List distributions
        run: ls -l dist

      # 使用 pypa action 发布到 PyPI
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
